# -*- coding: utf-8 -*-
"""Multiple linear

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uVvF5fH_Os64MTeVkFWd7uoaSvzrWzZr
"""

import matplotlib.pyplot as plt
import pandas as pd
from sklearn import linear_model
from sklearn.metrics import r2_score
import numpy as np

url="https://raw.githubusercontent.com/jadijadi/machine_learning_with_python_jadi/main/FuelConsumption.csv"
d=pd.read_csv(url)
d

"""
co2 emission y axis"""

d.head(5)

d.describe()

d.columns

m=np.random.rand(10)
print(m)
ma=m<0.8
ma

mask=np.random.rand(len(d))<0.8 # 80% True, 80 is for train.
mask
print(len(d))
train=d[mask]
print(len(train))
test=d[~mask]
print(len(test))

model=linear_model.LinearRegression()
train_x=train[['ENGINESIZE','CYLINDERS','FUELCONSUMPTION_CITY']]
train_y=train[['CO2EMISSIONS']]
model.fit(train_x,train_y)
a=model.coef_
c=model.intercept_
print("coefficint is",a,"and the intercept is",c)

test_x=test[['ENGINESIZE','CYLINDERS','FUELCONSUMPTION_CITY']]
test_y=test[['CO2EMISSIONS']]
test_p=model.predict(test_x)
r2=r2_score(test_p,test_y)
print(r2)